inherit_from: .rubocop_todo.yml
inherit_gem:
  gc_ruboconfig: rubocop.yml

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable

Layout/LineLength:
  Max: 100

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec

Gemspec/RequiredRubyVersion:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Max: 15

