version: 2

references:
  steps: &steps
    - checkout

    - type: cache-restore
      key: anony-bundler-{{ checksum "anony.gemspec" }}

    - run: gem install bundler -v 2.1.4
    - run: bundle config set path 'vendor/bundle'
    - run: bundle install

    - type: cache-save
      key: anony-bundler-{{ checksum "anony.gemspec" }}
      paths:
        - vendor/bundle

    - type: shell
      command: |
        bundle exec rspec --profile 10 \
                          --format RspecJunitFormatter \
                          --out /tmp/test-results/rspec.xml \
                          --format progress \
                          spec

    - type: store_test_results
      path: /tmp/test-results

    - run: bundle exec rubocop --parallel --extra-details --display-style-guide

jobs:
  ruby24-rails52:
    docker:
      - image: ruby:2.4
        environment:
          - RAILS_VERSION=5.2
    steps: *steps
  ruby25-rails52:
    docker:
      - image: ruby:2.5
        environment:
          - RAILS_VERSION=5.2
    steps: *steps
  ruby25-rails60:
    docker:
      - image: ruby:2.5
        environment:
          - RAILS_VERSION=6.0
    steps: *steps
  ruby26-rails52:
    docker:
      - image: ruby:2.6
        environment:
          - RAILS_VERSION=5.2
    steps: *steps
  ruby26-rails60:
    docker:
      - image: ruby:2.6
        environment:
          - RAILS_VERSION=6.0
    steps: *steps
  ruby27-rails52:
    docker:
      - image: ruby:2.7
        environment:
          - RAILS_VERSION=5.2
    steps: *steps
  ruby27-rails60:
    docker:
      - image: ruby:2.7
        environment:
          - RAILS_VERSION=6.0
    steps: *steps

workflows:
  version: 2
  tests:
    jobs:
      - ruby24-rails52
      - ruby25-rails52
      - ruby25-rails60
      - ruby26-rails52
      - ruby26-rails60
      - ruby27-rails52
      - ruby27-rails60
