version: 2.1

jobs:
  test:
    parameters:
      ruby-version:
        type: string
      rails-version:
        type: string

    docker:
      - image: ruby:<<parameters.ruby-version>>
        environment:
          - RAILS_VERSION=<<parameters.rails-version>>
    steps:
      - checkout

      - restore_cache:
          key: anony-bundler-{{ checksum "anony.gemspec" }}

      - run: gem install bundler -v 2.1.4
      - run: bundle config set path 'vendor/bundle'
      - run: bundle install

      - save_cache:
          key: anony-bundler-{{ checksum "anony.gemspec" }}
          paths:
            - vendor/bundle

      - run:
          command: |
            bundle exec rspec --profile 10 \
                              --format RspecJunitFormatter \
                              --out /tmp/test-results/rspec.xml \
                              --format progress \
                              spec

      - store_test_results:
          path: /tmp/test-results

      - run: bundle exec rubocop --parallel --extra-details --display-style-guide

  publish:
    parameters:
      ruby-version:
        type: string

    docker:
      - image: ruby:<<parameters.ruby-version>>

    steps:
      - checkout
      - run:
          name: Check gem version
          command: |
            ANONY_VERSION=$(ruby -r ./lib/anony/version.rb -e "puts Anony::VERSION")
            GIT_TAG=$(git describe --tags)
            [ "${GIT_TAG}" == v"${ANONY_VERSION}" ] && exit 0
            echo "Failed version check (git:${GIT_TAG} gem:${ANONY_VERSION})"
            exit 1
      - run:
          name: Create credentials file
          command: |
            mkdir -p $HOME/.gem
            touch $HOME/.gem/credentials
            chmod 0600 $HOME/.gem/credentials
      - run:
          name: Setup credentials
          command: |
            printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
      - run:
          name: Gem build
          command: gem build anony.gemspec -o anony-release.gem
      - run:
          name: Gem publish
          command: gem push anony-release.gem

workflows:
  version: 2
  test-and-publish:
    jobs:
      - test:
          matrix:
            parameters:
              ruby-version: ["2.4", "2.5", "2.6", "2.7"]
              rails-version: ["5.2", "6.0"]
            exclude:
              - ruby-version: "2.4"
                rails-version: "6.0"
      - publish:
          ruby-version: "2.7"
          requires:
            - test
          filters:
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+/
            branches:
              ignore: /.*/
