version: 2

references:
  steps: &steps
    - checkout

    - type: cache-restore
      key: anony-bundler-{{ checksum "anony.gemspec" }}

    - run: gem install bundler -v 2.0.2
    - run: bundle install --path vendor/bundle

    - type: cache-save
      key: anony-bundler-{{ checksum "anony.gemspec" }}
      paths:
        - vendor/bundle

    - type: shell
      command: |
        bundle exec rspec --profile 10 \
                          --format RspecJunitFormatter \
                          --out /tmp/test-results/rspec.xml \
                          --format progress \
                          spec

    - type: store_test_results
      path: /tmp/test-results

    - run: bundle exec rubocop --parallel --extra-details --display-style-guide

jobs:
  ruby24:
    docker:
      - image: ruby:2.4
    steps: *steps
  ruby25:
    docker:
      - image: ruby:2.5
    steps: *steps
  ruby26:
    docker:
      - image: ruby:2.6
    steps: *steps

workflows:
  version: 2
  tests:
    jobs:
      - ruby24
      - ruby25
      - ruby26
