version: 2.1

jobs:
  test:
    parameters:
      ruby-version:
        type: string
      rails-version:
        type: string

    docker:
      - image: cimg/ruby:<<parameters.ruby-version>>
        environment:
          - RAILS_VERSION=<<parameters.rails-version>>
    steps:
      - checkout

      - restore_cache:
          key: anony-bundler-{{ checksum "anony.gemspec" }}

      - run: gem install bundler -v 2.2.33
      - run: bundle config set path 'vendor/bundle'
      - run: bundle install

      - save_cache:
          key: anony-bundler-{{ checksum "anony.gemspec" }}
          paths:
            - vendor/bundle

      - run:
          command: |
            bundle exec rspec --profile 10 \
                              --format RspecJunitFormatter \
                              --out /tmp/test-results/rspec.xml \
                              --format progress \
                              spec

      - store_test_results:
          path: /tmp/test-results

      - run: bundle exec rubocop --parallel --extra-details --display-style-guide

workflows:
  version: 2
  tests:
    jobs:
      - test:
          matrix:
            parameters:
              ruby-version: ["2.6", "2.7", "3.0"]
              rails-version: ["6.0", "6.1", "7.0"]
