name: tests

on:
  push:

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Run rubocop
        run: bundle exec rubocop --parallel --extra-details --display-style-guide

  tests:
    strategy:
      matrix:
        ruby-version: [2.6, 2.7, 3.0, 3.1]
        rails-version: [6.0, 6.1, 7.0]
        exclude:
          - ruby-version: 2.6
            rails-version: 7.0
    runs-on: ubuntu-latest
    env:
      RAILS_VERSION: ${{ matrix.rails-version }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: "${{ matrix.ruby-version }}"
      - name: Run tests
        run: bundle exec rspec --format RSpec::Github::Formatter
