name: tests

on:
  push:

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Run rubocop
        run: bundle exec rubocop --parallel --extra-details --display-style-guide

  # Exclusions based on table at https://www.fastruby.io/blog/ruby/rails/versions/compatibility-table.html
  tests:
    strategy:
      matrix:
        ruby-version: [2.6, 2.7, 3.0, 3.1, 3.2, 3.3]
        rails-version: [6.0, 6.1, 7.0, 7.1]
        exclude:
          - ruby-version: 2.6
            rails-version: 7.0
          - ruby-version: 2.6
            rails-version: 7.1
          - ruby-version: 3.0
            rails-version: 6.0
          - ruby-version: 3.1
            rails-version: 6.0
          - ruby-version: 3.2
            rails-version: 6.0
          - ruby-version: 3.3
            rails-version: 6.0
    runs-on: ubuntu-latest
    env:
      RAILS_VERSION: ${{ matrix.rails-version }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: "${{ matrix.ruby-version }}"
      - name: Run tests
        run: bundle exec rspec --format RSpec::Github::Formatter
